version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 6969:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./mysql-data:/var/lib/mysql